# config/routes.yaml

controllers:
    resource: ../src/Controller/
    type: attribute

# Garde tes autres routes manuelles si tu en as
api_login_check:
    path: /api/login_check
    methods: [POST]
